"""Render the public commit topic aggregate as an SVG profile card.

Purpose:
    Produce a compact right-aligned visual for GitHub profile README without
    requiring browser-side JavaScript or external image services.

Call graph:
    main -> parse_args -> load_aggregate -> render_svg -> write_svg
"""

from __future__ import annotations

import argparse
import html
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class RenderConfig:
    """Runtime parameters for SVG rendering.

    Attributes:
        aggregate_path: Public aggregate JSON generated by classify_commits.py.
        output_path: SVG file to write.
        width: SVG viewport width in pixels.
        height: SVG viewport height in pixels.
    """

    aggregate_path: Path
    output_path: Path
    width: int
    height: int


def parse_args() -> RenderConfig:
    """Parse explicit render paths and dimensions."""

    parser = argparse.ArgumentParser()
    parser.add_argument("--aggregate", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--width", type=int, default=760)
    parser.add_argument("--height", type=int, default=500)
    args = parser.parse_args()
    if args.width < 320:
        raise ValueError("--width must be at least 320")
    if args.height < 360:
        raise ValueError("--height must be at least 360")
    return RenderConfig(
        aggregate_path=Path(args.aggregate),
        output_path=Path(args.output),
        width=args.width,
        height=args.height,
    )


def load_aggregate(*, path: Path) -> dict[str, Any]:
    """Load public aggregate JSON used as the single render input."""

    return json.loads(path.read_text(encoding="utf-8"))


def text_element(
    *,
    x: int,
    y: int,
    text: str,
    size: int,
    weight: int = 400,
    fill: str = "#24292f",
) -> str:
    """Return an escaped SVG text element."""

    escaped_text = html.escape(text)
    return (
        f'<text x="{x}" y="{y}" font-family="Inter, ui-sans-serif, '
        f'system-ui, -apple-system, Segoe UI, sans-serif" font-size="{size}" '
        f'font-weight="{weight}" fill="{fill}">{escaped_text}</text>'
    )


def bar_row(
    *,
    x: int,
    y: int,
    width: int,
    label_width: int,
    label: str,
    count: int,
    total: int,
    color: str,
) -> str:
    """Render one horizontal category bar with count and percentage."""

    bar_x = x + label_width
    bar_width = max(4, round((width - label_width - 92) * count / total))
    pct = f"{count / total * 100:.1f}%"
    return "\n".join(
        [
            text_element(x=x, y=y + 14, text=label, size=17, weight=600),
            (
                f'<rect x="{bar_x}" y="{y}" width="{width - label_width - 92}" '
                f'height="16" rx="4" fill="#eef2f7" />'
            ),
            (
                f'<rect x="{bar_x}" y="{y}" width="{bar_width}" '
                f'height="16" rx="4" fill="{color}" />'
            ),
            text_element(
                x=bar_x + width - label_width - 78,
                y=y + 14,
                text=f"{count} · {pct}",
                size=15,
                fill="#57606a",
            ),
        ]
    )


def monthly_strip(
    *,
    aggregate: dict[str, Any],
    x: int,
    y: int,
    width: int,
    categories: list[dict[str, Any]],
) -> str:
    """Render a 12-month activity strip colored by dominant topic."""

    months = sorted(aggregate["monthly_counts"].keys())[-12:]
    if len(months) == 0:
        return ""

    color_by_id = {category["id"]: category["color"] for category in categories}
    cell_gap = 5
    cell_width = max(10, (width - cell_gap * (len(months) - 1)) // len(months))
    pieces = [
        text_element(
            x=x,
            y=y - 12,
            text="Recent 12-month dominant topic strip",
            size=15,
            weight=600,
            fill="#57606a",
        )
    ]
    max_count = max(
        sum(aggregate["monthly_counts"][month].values()) for month in months
    )
    for index, month in enumerate(months):
        counts = aggregate["monthly_counts"][month]
        dominant = max(counts.items(), key=lambda item: item[1])[0]
        opacity = 0.35 + 0.65 * sum(counts.values()) / max_count
        cell_x = x + index * (cell_width + cell_gap)
        pieces.append(
            f'<rect x="{cell_x}" y="{y}" width="{cell_width}" height="28" '
            f'rx="5" fill="{color_by_id[dominant]}" opacity="{opacity:.2f}">'
            f'<title>{html.escape(month)} · {sum(counts.values())} commits</title>'
            "</rect>"
        )
    return "\n".join(pieces)


def render_svg(*, aggregate: dict[str, Any], width: int, height: int) -> str:
    """Render the complete SVG document from aggregate data."""

    categories = aggregate["categories"][:8]
    total = aggregate["total_commits"]
    body_width = width - 64
    rows = []
    start_y = 128
    for index, category in enumerate(categories):
        rows.append(
            bar_row(
                x=32,
                y=start_y + index * 38,
                width=body_width,
                label_width=250,
                label=category["label"],
                count=category["count"],
                total=total,
                color=category["color"],
            )
        )

    strip_y = start_y + len(categories) * 38 + 32
    subtitle = (
        f"{total:,} commits · {aggregate['public_repo_count']} public repos · "
        f"{aggregate['private_repo_count']} private repos"
    )
    privacy_note = "Raw private messages stay local; chart uses aggregate counts."

    svg_parts = [
        (
            f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" '
            f'height="{height}" viewBox="0 0 {width} {height}" role="img" '
            f'aria-label="Commit topic map">'
        ),
        '<rect width="100%" height="100%" rx="18" fill="#ffffff" />',
        (
            f'<rect x="1" y="1" width="{width - 2}" height="{height - 2}" '
            f'rx="18" fill="none" stroke="#d0d7de" />'
        ),
        text_element(x=32, y=48, text="Commit Topic Map", size=30, weight=800),
        text_element(x=32, y=78, text=subtitle, size=17, fill="#57606a"),
        text_element(x=32, y=104, text=privacy_note, size=14, fill="#6e7781"),
        "\n".join(rows),
        monthly_strip(
            aggregate=aggregate,
            x=32,
            y=strip_y,
            width=body_width,
            categories=aggregate["categories"],
        ),
        "</svg>",
    ]
    return "\n".join(svg_parts)


def write_svg(*, output_path: Path, svg: str) -> None:
    """Write the SVG as UTF-8 text."""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(svg + "\n", encoding="utf-8")


def main() -> None:
    """Load aggregate data and render the SVG."""

    config = parse_args()
    aggregate = load_aggregate(path=config.aggregate_path)
    svg = render_svg(
        aggregate=aggregate,
        width=config.width,
        height=config.height,
    )
    write_svg(output_path=config.output_path, svg=svg)
    print(f"rendered {config.output_path}")


if __name__ == "__main__":
    main()
